spring:
  application:
    name: geoj-backend-judge-service
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.130.16.185:3306/ge_oj
    username: madou1
    password: 789159357Zj
  # Redis 配置
  redis:
    database: 1
    host: 8.130.16.185
    port: 6379
    timeout: 5000
    password: 789159357Zj
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  cloud:
    nacos:
      discovery:
        server-addr: 172.17.0.2:8848
  rabbitmq:
    host: 172.17.0.3
    port: 5672
    username: guest
    password: 789159357Zj
    listener:
      direct:
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 5000
          multiplier: 1.5
          max-interval: 60000
  config:
    activate:
      on-profile:
        - prod
server:
  address: 0.0.0.0
  port: 8104
  servlet:
    context-path: /api/judge
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
        path: /api
        secure: false
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 代码沙箱配置
codesandbox:
  type: remote
  hostUrl: "http://172.17.0.5:8091/executeCode"
knife4j:
  enable: true
